### ISSUE TITLE
Cannot select OpenPGP Key id

### ISSUE THREAD

**Issue by robinwils** [android-password-store/Android-Password-Store#580] opened 2019-11-25 14:18 UTC
Hi,

Recently, when trying to show a password, I witnessed a screen slide back and forth, returning to the entry in the password tree without prompting my passphrase or displaying an error message. I updated, cleared cache, reinstalled both applications but now I have the same problem when selecting an OpenPGP Key id in the menu (screen slide back and forth without anything happening). I'm on Redmi Note 7.

Here is a [logcat segment](https://github.com/android-password-store/Android-Password-Store/files/3886784/adb-logcat.log) during the problem.

Let me know if you need more info.

Cheers

**Comment by Fuco1** [comment] 2019-11-26 15:46
Same issue on MI 9t

**Comment by msfjarvis** [comment] 2019-11-26 15:49
The logcat has nothing, and it's not really our bug. Dupe of https://github.com/android-password-store/Android-Password-Store/issues/518, refer to it for steps for resolving OEM specific shenanigens that break OpenKeychain in the first place.

**Closed by msfjarvis** 2019-11-26 15:49 UTC

**Comment by robinwils** [comment] 2019-11-27 13:11
Sorry for the duplicate, Using Password Store & Open Keychain in split view fixed this for me, thanks !
