### ISSUE TITLE
[BUG] Odd autofill behavior with TD Canada app

### ISSUE THREAD

**Issue by Gigahawk** [android-password-store/Android-Password-Store#769] opened 2020-05-09 10:52 UTC
**Describe the bug**
Using the new Oreo autofill on the TD Canada app causes the username of the selected file to be pasted into the first available textbox. 
The password is never pasted anywhere.

This issue did not occur with the old autofill mechanism.

**To Reproduce**
1. Open TD Canada
2. Attempt to use autofill
3. Username is pasted (instead of password) and always into the first available textbox

**Expected behavior**
- Password should be pasted into password field
- Username should be pasted into username field (?)

**Screenshots**

The autofill prompt shows up on the username field for some reason, and gets filled with the username when selected.
https://imgur.com/JBXSiYU.mp4
![zku1FKu](https://user-images.githubusercontent.com/10356230/81471515-744ca480-91a6-11ea-8060-9681390f447b.gif)

Selecting a password in the password prompt leads to the username being written to the username field
https://imgur.com/U6a3Vai.mp4
![sxgGtGd](https://user-images.githubusercontent.com/10356230/81471553-bf66b780-91a6-11ea-9b38-373b856771b9.gif)

Selecting a password in the password prompt when a card is already saved leads to the username being written to the password field (note the 13 dots equal in length to `online_sample`)
https://i.imgur.com/I0HF5Wx.mp4
![SHs548X](https://user-images.githubusercontent.com/10356230/81471458-19b34880-91a6-11ea-972c-134c45ed4359.gif)

**Device information (please complete the following information):**
 - Device: Oneplus 6
 - OS: Oxygen OS Android version 9.0
 - App version 1.7.2

**Additional context**
- Videos above were recorded in 1.7.1, the issue is reproducible in 1.7.2.
- The password value of `online_sample` used in the videos above is `thisisalongpassword`, which has 19 characters. 
- Link to app in question https://play.google.com/store/apps/details?id=com.td&hl=en_CA

**Comment by FabianHenneke** [comment] 2020-05-09 15:11
Thank you for the very detailed report, especially the videos!

The root cause is that TD Canada messed up the `inputType` on their password field: It has the `TYPE_TEXT_VARIATION_PASSWORD` set, but is not even of `TYPE_CLASS_TEXT` (it has no valid class). Well, apparently our versions of Android are fine with that and still apply password masking, but it certainly makes the login form less accessible.

I'm unsure about how to proceed here: I can easily drop the check for `TYPE_CLASS_TEXT` in Autofill, but I don't want to risk filling into non-masked text fields as the precise behavior of such "password" fields is undefined. I can take a look at AOSP sources when I have time and try to reverse engineer the effects of this.

@msfjarvis What are your thoughts on this?

**Comment by msfjarvis** [comment] 2020-05-09 15:28
> Thank you for the very detailed report, especially the videos!
> 
> The root cause is that TD Canada messed up the `inputType` on their password field: It has the `TYPE_TEXT_VARIATION_PASSWORD` set, but is not even of `TYPE_CLASS_TEXT` (it has no valid class). Well, apparently our versions of Android are fine with that and still apply password masking, but it certainly makes the login form less accessible.
> 
> I'm unsure about how to proceed here: I can easily drop the check for `TYPE_CLASS_TEXT` in Autofill, but I don't want to risk filling into non-masked text fields as the precise behavior of such "password" fields is undefined. I can take a look at AOSP sources when I have time and try to reverse engineer the effects of this.
> 
> @msfjarvis What are your thoughts on this?

I'm personally not very comfortable with the prospect of creating a possibility of filling passwords into the wrong fields. If there's absolutely no way to get TD Canada to address this then we can probably think about going forward with opening that can of worms.

**Comment by FabianHenneke** [comment] 2020-05-09 17:29
[A search on androidxref](http://androidxref.com/9.0.0_r3/search?q=&defs=&refs=TYPE_TEXT_VARIATION_PASSWORD&path=&hist=&project=frameworks) shows that `TYPE_TEXT_VARIATION_PASSWORD` is only considered by core Android classes if it shows up in tandem with `TYPE_CLASS_TEXT`. On that basis, I don't even know how TD Canada's login form manages to mask the password, but maybe they just rely on a custom text field class.

@Gigahawk I'm sorry that we can't offer a quick fix, but I will have to label this as 'wontfix'. We can leave the issue open though while you ask TD Canada to fix their app and think about other solutions once they fail to do so.

**Comment by Gigahawk** [comment] 2020-05-10 04:59
Well I couldn't find a way to submit a bug to the app developers but the email listed on the Play Store is just a standard customer support email so we'll see if I get a response.

**Comment by FabianHenneke** [comment] 2020-06-22 18:23
@Gigahawk Have you heard back from TD Canada?

**Comment by Gigahawk** [comment] 2020-06-22 18:27
Aside from a promise that it's been forwarded to tech support, nope.

**Comment by FabianHenneke** [comment] 2020-06-22 18:41
@Gigahawk I feared as much... I will close this for now as there is not really anything we could do that doesn't have negative side effects. But feel free to post here if you should get a response at some time or find the issue to have been fixed.

**Closed by FabianHenneke** 2020-06-22 18:41 UTC
Labels: ⏳ waiting-on-reporter, 🗑 wontfix
