### ISSUE TITLE
[BUG]Android-9 . Can't open subwondow

### ISSUE THREAD

**Issue by brothermechanic** [android-password-store/Android-Password-Store#579] opened 2019-11-24 03:39 UTC
**Describe the bug**
I cannot open new subwindow now

**To Reproduce**
see video fom my screen
[PasswordStore.zip](https://github.com/android-password-store/Android-Password-Store/files/3883178/PasswordStore.zip)
Version 1.3.2
It happend now with 1.2x versions too(

**Comment by msfjarvis** [comment] 2019-11-24 03:58
Duplicate of #518, read the discussion there for tips on how to workaround MIUI's braindamage.

**Closed by msfjarvis** 2019-11-24 03:58 UTC

**Comment by brothermechanic** [comment] 2019-11-24 12:37
Thank you very much!
![Screenshot_2019-11-24-15-36-11-138_com miui securitycenter](https://user-images.githubusercontent.com/3109995/69494751-5200ec00-0ed0-11ea-9a16-112e10366b21.jpg)
Works!
