### ISSUE TITLE
Support for ed25519 key type

### ISSUE THREAD

**Issue by ismail** [android-password-store/Android-Password-Store#794] opened 2020-05-25 06:48 UTC
Trying to import ed25519 [0] formatted SSH private/pubkey pair doesn't work, which I think only RSA key-type formatted is supported at the moment? It'd be nice to support ed25519 keys as well.

[0] https://tools.ietf.org/id/draft-ietf-curdle-ssh-ed25519-02.html

**Comment by msfjarvis** [comment] 2020-05-25 06:53
Support for modern key ciphers will need a large rewrite that would unfortunately also regress some features so we're not committing to it right now. The issue is also a duplicate of #448 so I'm closing it.

**Closed by msfjarvis** 2020-05-25 06:53 UTC
