### ISSUE TITLE
[BUG] Can't look a password!

### ISSUE THREAD

**Issue by Geradot** [android-password-store/Android-Password-Store#592] opened 2019-12-13 07:13 UTC
**Describe the bug**
I try to choose any entry with password in my list, but it throws me back to the list of all entries. And it seems that the matter does not even reach the launch of the OpenKeychain application to request a GPG key.

**To Reproduce**
1. Go to 'Password Store'
2. Click on any entry.
3. See error.

**Expected behavior**
I expected to happen the OpenKeychain should opening. After that I must to input a password for my GPG-key.

**Device information (please complete the following information):**
 - Device: Xiaomi Redmi Note 7 (MIUI 11)
 - OS: Android 9
 - App version 1.3.3

**Additional context**
I don't have the problem in GNU/Linux.

**Comment by msfjarvis** [comment] 2019-12-13 08:19
Duplicate of #518

**Closed by msfjarvis** 2019-12-13 08:19 UTC
