### ISSUE TITLE
[BUG] force open of "draw on top of other app" setting

### ISSUE THREAD

**Issue by siwan05** [android-password-store/Android-Password-Store#835] opened 2020-06-06 17:33 UTC
**Describe the bug**
When you click a password field it jumps to settings to allow passwordstore to draw on top of other apps even though it has already been allowed. When attempting to go back it jumps straight back to the setting.

Video showing the issue: https://photos.app.goo.gl/RQSXankMjLu67uAw6

**To Reproduce**
1. Go to fill in a password
2. Click on the password field

**Expected behavior**
It allows you to select a password

**Device information (please complete the following information):**
 - Device: [OnePlus 7t pro]
 - OS: [e.g. ParanoidAndroid Android version 10.0]
 - App version [1.8.1]

**Comment by msfjarvis** [comment] 2020-06-06 17:35
Please search through the issues, both open and closed, before opening new ones. This is a duplicate of #767 and was fixed by #827.

**Closed by msfjarvis** 2020-06-06 17:35 UTC
