### ISSUE TITLE
[BUG] Autofill password generation transparent overlay

### ISSUE THREAD

**Issue by xdevs23** [android-password-store/Android-Password-Store#814] opened 2020-05-30 18:09 UTC
**Describe the bug**
When generating a password from autofill, instead of pasting the generated password, it only displays a transparent-gray overlay on top of the app that I was using. I can't tap on anything in the app, I need to leave the app and open it again from the launcher (doesn't have to be killed).

**To Reproduce**
1. Open Firefox Preview (or any other app that is supported)
2. Go to a website which you need to enter an username and password on
3. Tap on username password field
4. Autofill pop-up appears, tap on "Generate password"
5. Generate the password and save it
6. Now you see a gray overlay on top of the app

**Expected behavior**
After saving the generated password, it should be entered into the appropriate password field on the website, app etc.

**Screenshots**
![image](https://user-images.githubusercontent.com/6959245/83336071-0a10b680-a2b1-11ea-842e-185d24958410.png)
![image](https://user-images.githubusercontent.com/6959245/83336076-0f6e0100-a2b1-11ea-9463-dc1a39c591e6.png)

**Device information:**
 - Device: OnePlus 5
 - OS: halogenOS 10 Custom/AOSP ROM (Android 10 r36 / May security patch)
 - App version: 1.9.0-SNAPSHOT (Downloaded on May 30)

**Additional context**
So far this has happened to me in various apps, for example Chrome Beta and Firefox Preview in at least two versions of Password Store.

**Comment by FabianHenneke** [comment] 2020-05-30 18:41
I have identified at least one issue that could result in this malfunction of the Autofill generate action. Are you using Password Store without a git repository by any chance? You can confirm that by checking that the Password Store settings *don't* show a "Generate SSH key pair" option for you.

@msfjarvis [This line](https://github.com/android-password-store/Android-Password-Store/blame/2428d4c0deb5d088112ed10391932acf325e84d5/app/src/main/java/com/zeapo/pwdstore/PasswordStore.kt#L842) should honor `finishWithResultOnEnd`. I will submit a PR.

**Comment by msfjarvis** [comment] 2020-05-30 18:44
> @msfjarvis [This line](https://github.com/android-password-store/Android-Password-Store/blame/2428d4c0deb5d088112ed10391932acf325e84d5/app/src/main/java/com/zeapo/pwdstore/PasswordStore.kt#L842) should honor `finishWithResultOnEnd`. I will submit a PR.

sigh :man_facepalming:. Thanks for fixing this up, I'm working on a full revamp of the decrypt screen UI atm.

**Comment by xdevs23** [comment] 2020-05-30 18:48
> Are you using Password Store without a git repository by any chance?

I am using git over SSH. The repository is on a server.

![image](https://user-images.githubusercontent.com/6959245/83336827-e8b2c900-a2b6-11ea-9c47-2d0a111ed5e8.png)

**Comment by FabianHenneke** [comment] 2020-05-30 18:56
I have created a potential fix in #815. Once this has been merged and a few minutes have passed, could you try again with the then new snapshot build? 

I'm unsure what the cause of this could be if not #815, but will keep looking. Were you able to use Autofill password generation e.g. with version 1.6.0?

**Comment by xdevs23** [comment] 2020-05-30 19:03
Previously I was using APS 1.8.0 which has the same issue, before that I was using a version from the Play Store that did not have Autofill.

**Comment by FabianHenneke** [comment] 2020-05-30 19:13
The new snapshot build is out: https://dl.msfjarvis.dev/APS/. Could you give it a try?

> Previously I was using APS 1.8.0 which has the same issue, before that I was using a version from the Play Store that did not have Autofill.

Thanks, that will help our investigation.

**Comment by xdevs23** [comment] 2020-05-30 19:18
It works now. After saving, the app goes away and inserts the username and password into the website.

Thanks for fixing it so quickly! :smile:

**Comment by FabianHenneke** [comment] 2020-05-30 19:20
> It works now. After saving, the app goes away and inserts the username and password into the website.
> 
> Thanks for fixing it so quickly!

Glad that it worked!

@msfjarvis It seems that isGitRepo() returned inconsistent results in this case (between UserPreference and AutofillSaveActivity). Do you have an idea how this could happen?

**Closed** 2020-05-30 19:20 UTC
Labels: 🐛 bug

**Comment by msfjarvis** [comment] 2020-05-30 19:22
> > It works now. After saving, the app goes away and inserts the username and password into the website.
> > Thanks for fixing it so quickly!
> 
> Glad that it worked!
> 
> @msfjarvis It seems that isGitRepo() returned inconsistent results in this case (between UserPreference and AutofillSaveActivity). Do you have an idea how this could happen?

Not quite sure honestly. There's no committing being done in that section so the object database couldn't have changed, and we're not fetching so `getAllRefs` can't have changed either.
