### ISSUE TITLE
[BUG] Save not working after Android 10 update

### ISSUE THREAD

**Issue by ulfi** [android-password-store/Android-Password-Store#714] opened 2020-04-16 15:34 UTC
**Describe the bug**
Sony Xperia  XZ2 with update to Android 10.
Key Provider: OpenKeychain Version 5.5 (55000), App Passwod Store included in Apps, 4 (private) Keys selected.
With last release 1.6.0 (only from playstore, so in f-droid stil the old Version). The APP starts now with usage oft local folder (the SmartDrive folder synct via FolderSyncPro with my WebDAVs folder) selected as external Repository. The existing pass files can be opened normaly. Only if I will edit them, the Save button is not working. Same with a new created "New Password"

**To Reproduce**
1. Open PasswordStore
2. Open an existing (or new) password file and go in edit mode 
3. change someting
4. press save button (similar with save and copy button) 
5. "Bitte setzen sie einen Pfad" (EN: free translated "Please set a path") accures
6. Editing dialog is still open and not saved
7. Closing only with back button possible

**Expected behavior**
Save Button is not reacting, only possible solution to leave is the back button. So it seems that either there is no connection to OpenKeychain or storage (access) isn't possible.
There are a short message on the bottom DE: "Bitte setzen sie einen Pfad" (EN: free translated "Please set a path"). But the Path is selected and rights are permitted (verified in the App Settings of Android - access allowed).

**Screenshots**
Screenshot isn't allowed/possible

**Device information (please complete the following information):**
 - Device: Sony Xperia XZ2 (H8266)
 - OS: stock ROM (upgrade) Android Version 10 Build 52.1.A.0.672  
 - App version: 1.6.0
- Key Provider: OpenKeychain Version 5.5 (55000), 
- App PasswordStore included in connected Apps (of OpenKeychain), 4 (private) Keys selected.

**Additional context**
n/a

Status: nicht begonnen

--
Geteilt mit OpenTasks

**Comment by ulfi** [comment] 2020-04-16 15:38
Request in Playstore to add an item from "Harsh Shandilya" at 15.04.20

**Comment by msfjarvis** [comment] 2020-04-16 15:39
Thanks for the report! The issue is fixed for the next release, you can confirm that by going to the README and downloading the Snapshot build linked there which contains all the work that will go into the next release.

**Comment by ulfi** [comment] 2020-04-16 17:27
Thanks @msfjarvis 
Only I can't install the new snapshot (only the message "error" will be shown if i open the apk on my phone
https://dl.msfjarvis.dev/APS/aps_1.7.0-SNAPSHOT.apk

Short question, in f-droid still there is version 1.3.3 (so the old branch), isn't there an update requested at f-droid?

**Comment by msfjarvis** [comment] 2020-04-16 17:31
> Thanks @msfjarvis
> Only I can't install the new snapshot (only the message "error" will be shown if i open the apk on my phone
> [dl.msfjarvis.dev/APS/aps_1.7.0-SNAPSHOT.apk]
(https://dl.msfjarvis.dev/APS/aps_1.7.0-SNAPSHOT.apk)

APK seems to work fine on my devices, do you have a screenshot of the error?

> Short question, in f-droid still there is version 1.3.3 (so the old branch), isn't there an update requested at f-droid?

For now, yes. We're preparing to upload a new listing with v1.7.0 when it is pushed to the Play Store, progress can be tracked at #648

**Comment by ulfi** [comment] 2020-04-16 17:57
Now, I installed it from an other filemanager, and installation works.

But after selection of external repository, they are not present in the field. But after restart it works.

Remark: Seems to be an issue with Bouncer
https://play.google.com/store/apps/details?id=com.samruston.permission
which are not allowed to overlay the PasswordStore - to show me the message to allow the access rights.

Now changes works fine - grate work :+1: 

Remark: The "Extra" field will be overlayed by the keyboard, and scrolling isn't possible - see pictures (if I can upload them)

**Comment by ulfi** [comment] 2020-04-16 18:15
I can't find how to share the pictures. So I copied it to my Webspace:
https://c.1und1.de/@519803974291816561/VUTxg6PHQ3yhDnx_DV4KCw
PIN: 10714
(Remark: file will be deleted in some days)
I included also the screenshot of the error which accrued during the settings adaption.
But how I can find the copy of the error :-(

**Comment by ulfi** [comment] 2020-04-16 18:46
Remark OT: Update in f-droid store requested (if possible switch to auto-update)
https://gitlab.com/fdroid/fdroiddata/-/issues/2015

**Comment by msfjarvis** [comment] 2020-04-16 18:52
> Remark OT: Update in f-droid store requested (if possible switch to auto-update)
> https://gitlab.com/fdroid/fdroiddata/-/issues/2015
> 

Appreciate that but the issue was rather unnecessary, we've got things figured out on our end.

**Comment by ulfi** [comment] 2020-04-16 20:00
> Appreciate that but the issue was rather unnecessary, we've got things figured out on our end.
OK - tanks

Let me know if you have downloaded the pictures (or don't need them anymore), then I will delete the File&Link

**Comment by ulfi** [comment] 2020-04-18 15:02
@msfjarvis 
I've a finding with the 1.7.0 preview:
- The opened password store wouldn't be closed after the time the password is present in the clipboard. I'm not sure, but so I remind well, in the past at this time the open dialog with the password was closed
- Like mentioned above, the extended information isn't scrolling during typing, so it is partly not visible.

Should I open after evaluation if the bug exists two issue for this?

**Comment by msfjarvis** [comment] 2020-04-18 15:12
> * The opened password store wouldn't be closed after the time the password is present in the clipboard. I'm not sure, but so I remind well, in the past at this time the open dialog with the password was closed

I'm sorry, I don't think I really understand what you mean here. Some sort of screen recording would perhaps help.

> * Like mentioned above, the extended information isn't scrolling during typing, so it is partly not visible.

I do believe I made things scrollable. Would you be able to provide a screenshot of the page that is not scrolling?

**Comment by msfjarvis** [comment] 2020-04-19 09:47
Just realized the snapshots were failing to deploy after a server switch didn't migrate the SSH keys required to authenticate. @ulfi can you try again? I've synced the snapshot to master.

**Comment by senseicoder** [comment] 2020-04-20 20:52
Hi, 

Same problem on Oppo A5 2020, Android 9 : save and save/copy buttons don't do anything, but I have no message. I try 1.7.0 apk

**Comment by msfjarvis** [comment] 2020-04-23 21:18
I'm fairly confident this is a non-issue on the newest version and the reporter is not responsive so I'll go ahead and close this.

**Closed** 2020-04-23 21:19 UTC
