### ISSUE TITLE
bad behavior with external non-git repo

### ISSUE THREAD

**Issue by edrex** [android-password-store/Android-Password-Store#226] opened 2016-09-27 20:46 UTC
| The first time, this error is seen, and an empty `.git` dir is created: | Subsequently, this error is seen: |
| --- | --- |
| ![screenshot_20160927-134002](https://cloud.githubusercontent.com/assets/14615/18891030/72d79b9a-84b8-11e6-98f6-a5baf8563758.png) | ![screenshot_20160927-133519](https://cloud.githubusercontent.com/assets/14615/18891042/7afdfa80-84b8-11e6-92ea-378fdc4d587d.png) |

I've decided to git-enable my repo, partly to work around this issue and partly because it's safer:

```
git init .
git add .
git commit -m "init: make my password store a git repo"
```

It's possible that the resolution to this issue is to tell the user that writing to non-git stores isn't supported, and offer to init the store as a git repo.

Follow-up to https://github.com/zeapo/Android-Password-Store/issues/41.

**Comment by msfjarvis** [comment] 2020-04-25 14:06
Duplicate of #86

**Closed by msfjarvis** 2020-04-25 14:07 UTC
