### ISSUE TITLE
Cannot Push to Computer

### ISSUE THREAD

**Issue by monkeynaleo** [android-password-store/Android-Password-Store#151] opened 2015-11-24 04:55 UTC
Whenever I try to push the new passwords that I have created back to my computer, It completes without error, but no files have been pushed!  Do i need to setup something special to get it to push changes back?

**Comment by noxamox23** [comment] 2016-05-20 20:13
Hi, I have a similar problem.
My configuration is:
- Password Store on Android (Android 6.0.1, copperhead OS, Nexus 5)
- pass, git, ssh etc. on a raspberry pi (jessie)

The initial stuff works fine - I created entries on the raspi with pass and can clone the data to Android. However, if I create an entry on Android I cannot propagate it to the raspi (not with Synchronise or Push). 
I am not that familiar with git but I have tried a few things to diagnose - no success. syslog on the raspi shows that the ssh-connection is established fine. pass/git on the raspi seems to work fine as well. I tested the pass-data on the raspi by exporting the gpg-keys from openchain. During the attemps I created several gits with some arbitrary key entries which I was able to merge into one bigger git with the usual syntax "pass git ...". 
Could it be a configuration problem on Android that somehow the changes there are marked as not-to-be-merged? I have tried to analyse the files on Android using an external repository (not the hidden one, I have no idea where that is located). I attach the git-config file below. Any ideas?

[core]
symlinks = false
repositoryformatversion = 0
filemode = false
logallrefupdates = true
[remote "origin"]
url = mylogin@xxx.xxx.xxx.xxx:.password-store
fetch = +refs/heads/*:refs/remotes/origin/*
pushurl = mylogin@xxx.xxx.xxx.xxx:.password-store
[branch "master"]
remote = origin
merge = refs/heads/master

**Comment by zeapo** [comment] 2016-05-20 21:25
Hi, is your repository a bare repository? 

A bare repository is a repo from which you can clone and to which you can push. 
Check with this command `git rev-parse --is-bare-repository`

**Comment by monkeynaleo** [comment] 2016-05-20 21:31
I get false for that command.  What am I supposed to do to fix it?

**Comment by noxamox23** [comment] 2016-05-21 00:16
Thanks, that was a very useful hint.

I also got a "false". I then did the following, based on these two references:
https://lists.zx2c4.com/pipermail/password-store/2015-October/001769.html
http://stackoverflow.com/questions/2199897/how-to-convert-a-normal-git-repository-to-a-bare-one

- Create a new directory pw.git on my raspi; make it bare:
mkdir pw.git
cd pw.git
git init --bare
- pointed to pw.git from Android -> voila, syncing worked as confirmed by using
git status; git log
- removed .password-store and created it again:
rm -fr .password-store; pass init <mypgpid>; pass git init
- configured the names:
pass git config user.email <myemail>; pass git config user.name <myname>
- pulling to .password-store:
pass git pull ~/pw.git
- I then automatised the propagation by adding in pw.git/hooks a file name "post-receive" with the following content:
#!/bin/bash
exec /usr/bin/pass git pull origin ~/pw.git
- Also gotta chmod u+x post-receive. 
- This propagates automatically at least in the direction of .password-store. I could not figure out the hook for the other direction, i.e. after "pass insert <newkey>" but a "pass git push ~/pw.git" does the job.

Does this make sense, or would you recommend a different approach?

**Comment by dersch81** [comment] 2016-11-02 12:12
@noxamox23 that way doesn't work for me. I can only push to the repo now from Android but not pull or sync. Besides i pull from the .password-store but it does not add any changes with the message already up to date.

**Comment by konfiot** [comment] 2016-12-17 16:01
Doesn't work for me, I can pull from my server to my phone, but pushing from the phone to the server doesn't work,  the repository is a bare repo, pushing from another PC works

**Comment by nuntius35** [comment] 2017-02-05 16:39
> I get false for that command. What am I supposed to do to fix it?

The following command fixed it for me. But I don't understand enough about git to know if this is a bad way of doing things.
`git config --local receive.denyCurrentBranch updateInstead`

**Comment by ve3sqd** [comment] 2017-02-20 02:22
The ironic thing about this problem is that the first line of the android password store github page says it tries to be 100% compatible with pass.  Yet, if you follow the instructions for setting up pass, it will not work properly with this app.  It will allow the initial clone, but will not push or pull after this.

I have a raspberry pi that I want to keep my repo on so I can push/pull at any time (the raspberry pi runs 24/7).  Here is how I got it to work.

1.  create your .password-store directory in the usual way on the raspberry pi following the instructions on the pass home page (https://www.passwordstore.org/).  Make sure you do the pass git init to initialise it as a git repository.
2.  the android password store app will not work properly unless the git repo is a bare repository.  So clone the .password-store repo with "git clone --bare .password-store password-store.git".  You will now have a bare git repository in your /home/userid directory that will work with android password-store.
3.  I run Linux Mint and wanted to have my password store available there.  I access the raspberry pi via ssh so did the following on my Mint machine:  "git clone username@raspberrypi:/home/username/password-store.git /home/username/.password-store".  I then had a password store on Mint that works normally using the "pass" commands.  So I can do all the normal maintenance (insert, rm, etc.) of my password store on Mint using the pass commands.  When done, "pass git push" will push the changes to the raspberry pi.
4.  next I installed android password store, selected 'clone server' and put in the address for /home/username/password-store.git on the raspberry pi.  It successfully cloned and populated the app.
5.  After this initial setup, push and pull worked as they should.

Once setup, this app works very nicely.

**Comment by zeapo** [comment] 2017-02-20 11:09
Sadly *tries to be* does not mean *is*.

On the other hand, the initialization of pass's git repo suggests to add a remote repository:
```
zx2c4@laptop ~ $ pass git init
Initialized empty Git repository in /home/zx2c4/.password-store/.git/
zx2c4@laptop ~ $ pass git remote add origin kexec.com:pass-store
```
Also, by default a git non-bare repository does not accept push commands by default. It's up to you to configure it.

**Comment by jes** [comment] 2017-05-07 19:26
At minimum, I think it's a bug not to show the user the error message from git.

I'm currently stuck in a similar situation, except my remote *is* a bare repo.

I believe the remote is out of sync with the phone (i.e. both have had changes) and so I can't pull or push without a merge, and the app doesn't support that. So it just acts like everything is fine, when actually I can no longer sync anything to/from the phone.

**Comment by zeapo** [comment] 2017-05-12 07:54
@jes Your issue is more of #280 than this issue. On the other hand, the "pull" button does a `pull --rebase`. 
The sync does a `pull --rebase` followed by a `push`. The issue is that sometimes during the rebase, conflicts happen, and to solve those conflicts we have to add a new layer that does the rebase step by step, checks for conflicts and asks the user if he[r] wants a `theirs` or `ours` strategy.
And this leads us to implement a git client rather than a password manager...

**Comment by jes** [comment] 2017-05-13 13:24
I understand you don't want to implement a full git client, but at the moment it is less than ideal that:

1.) You can very easily get the password manager stuck in such a state that it is impossible to sync any more, and
2.) There is absolutely no UI indication that this has happened.

**Comment by SpotlightKid** [comment] 2017-11-02 16:25
I have the same problem:

* Private repo on gitlab.com (so it should be bare, right?)
* Installed App on tablet and phone and cloned repo with app on both
* Added password entries on tablet and pushed: gitlab repo is updated properly and I can get the new entries on my PC with "pass git pull"
* Added password entries on phone.
* Tried to pull and push on phone: no error, but nothing is updated, neither the repo on the phone nor the repo on gitlab.com :(

There's also no indication (to me) that something went wrong in logcat. This is the part of the log from just before I tap OK in the SSH passphrase dialog (filtered by PID with grep):
```
11-02 17:22:32.581  2434  2719 I InputDispatcher: Delivering touch to (24347): action: 0x0, toolType: 1
11-02 17:22:32.586 24347 24347 D ViewRootImpl: ViewPostImeInputStage processPointer 0
11-02 17:22:32.676  2434  2719 I InputDispatcher: Delivering touch to (24347): action: 0x1, toolType: 1
11-02 17:22:32.676 24347 24347 D ViewRootImpl: ViewPostImeInputStage processPointer 1
11-02 17:22:32.706 24347 24347 W ResourceType: Failure getting entry for 0x01080a8c (t=7 e=2700) (error -75)
11-02 17:22:32.716 24347 24347 D ViewRootImpl: #1 mView = com.android.internal.policy.PhoneWindow$DecorView{ef7f6fb V.E...... R.....I. 0,0-0,0}
11-02 17:22:32.721  2434  2903 D InputDispatcher: Focus left window: 24347
11-02 17:22:32.721  2434  2903 D InputDispatcher: Focus entered window: 24347
11-02 17:22:32.726 24347 24524 D doInBackground: Executing the command <org.eclipse.jgit.api.PushCommand@df6d318>
11-02 17:22:32.736 24347 24347 D ViewRootImpl: #3 mView = null
11-02 17:22:32.781  2434  2701 V WindowStateAnimator: Finishing drawing window Window{5872826 u0 d0 p24347 com.zeapo.pwdstore/com.zeapo.pwdstore.git.GitActivity}: mDrawState=DRAW_PENDING
11-02 17:22:32.781 24347 24347 D ViewRootImpl: MSG_RESIZED_REPORT: ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
11-02 17:22:32.806  2434  3239 V WindowStateAnimator: Finishing drawing window Window{5872826 u0 d0 p24347 com.zeapo.pwdstore/com.zeapo.pwdstore.git.GitActivity}: mDrawState=HAS_DRAWN
11-02 17:22:32.811 24347 24347 E ViewRootImpl: sendUserActionEvent() mView == null
11-02 17:22:38.071 24347 24347 D ViewRootImpl: #3 mView = null
11-02 17:22:38.081  2434  2551 D StatusBarManagerService: manageDisableList userId=0 what=0x0 pkg=Window{ecfdc4d u0 d0 p24347 com.zeapo.pwdstore/com.zeapo.pwdstore.git.GitActivity}
11-02 17:22:38.086  2434  2471 D InputDispatcher: Focus left window: 24347
11-02 17:22:38.086  2434  2471 D InputDispatcher: Focus entered window: 24347
11-02 17:22:38.121 24347 24347 E ViewRootImpl: sendUserActionEvent() mView == null
11-02 17:22:38.181  2434  3239 D InputDispatcher: Focus left window: 24347
11-02 17:22:38.196 24347 24347 D REPO    : current path: /data/user/0/com.zeapo.pwdstore/files/store
11-02 17:22:38.251 24347 24347 D PASS    : Check, dir: /data/user/0/com.zeapo.pwdstore/files/store
11-02 17:22:38.261  2434  2551 D StatusBarManagerService: manageDisableList userId=0 what=0x0 pkg=Window{358e155 u0 d0 p24347 com.zeapo.pwdstore/com.zeapo.pwdstore.PasswordStore}
11-02 17:22:38.261  2434  2468 D InputDispatcher: Focus entered window: 24347
11-02 17:22:38.311  2434  2471 V WindowStateAnimator: Finishing drawing window Window{358e155 u0 d0 p24347 com.zeapo.pwdstore/com.zeapo.pwdstore.PasswordStore}: mDrawState=DRAW_PENDING
11-02 17:22:38.351 24347 24347 I Timeline: Timeline: Activity_idle id: android.os.BinderProxy@c149840 time:749672783
11-02 17:22:38.586 24347 24347 D ViewRootImpl: #3 mView = null
11-02 17:22:42.836 24347 24347 D ViewRootImpl: MSG_RESIZED_REPORT: ci=Rect(0, 48 - 0, 0) vi=Rect(0, 48 - 0, 0) or=2
11-02 17:22:42.941  2434  3039 V WindowStateAnimator: Finishing drawing window Window{358e155 u0 d0 p24347 com.zeapo.pwdstore/com.zeapo.pwdstore.PasswordStore}: mDrawState=DRAW_PENDING
```

Until this is fixed, I'm afraid the app is rather useless to me. :(

**Comment by msfjarvis** [comment] 2020-01-28 14:55
I cannot reproduce this on any of my devices nor with my local PC nor with github.com. Please let me know with a full device log if you can reproduce it on the latest [snapshot build](https://dl.msfjarvis.dev/APS)

**Closed by msfjarvis** 2020-01-28 14:55 UTC
